version: '3'
services:
  # MySQL 服務
  mysql:
    image: mysql:8.3.0
    container_name: clwy-api-mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=clwy1234
      - MYSQL_LOWER_CASE_TABLE_NAMES=0
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  # Node.js 服務
  app:
    build: .
    container_name: clwy-api-node
    ports:
      - "3039"  # 只需要暴露容器內部的 3039 端口即可，外部請求將由 Nginx 處理
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    environment:
      - DB_HOST=clwy-api-mysql
      - DB_USER=root
      - DB_PASSWORD=clwy1234
      - DB_PORT=3306
      - MYSQL_CONTAINER_PORT=${MYSQL_CONTAINER_PORT}

networks:
  web:
    external: true  # 確保該網絡是外部的，以便 Nginx 可以與 Node.js 進行通信